- name: task_2
  gather_facts: true
  hosts: all
  tasks:
    - name: install nginx on ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install apache2 on CentOS
      apt:
        name: apache2
        state: latest
      when: ansible_facts['distribution'] == "CentOS"

####################################################
############### restarting services ################
####################################################

    - name: restart nginx on ubuntu
      sysvinit:
        name: nginx
        state: restarted
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: restart apache2 on CentOS
      sysvinit:
        name: apache2
        state: restarted
      when: ansible_facts['distribution'] == "CentOS"